// ============================================================================
// FILE: app/api/export/markdown/route.ts
// PURPOSE: Export all achievements to downloadable Markdown file
// FORMAT: Professional resume-style document with stats
// ============================================================================

import { NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/db";

export async function GET() {
    try {
        // ============================================================
        // STEP 1: Authentication
        // ============================================================
        const session = await auth();

        if (!session?.user?.id) {
            return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
        }

        // ============================================================
        // STEP 2: Fetch All Achievements with Content
        // TODO: Load user's achievements + generated content
        // ============================================================
        const achievements = await prisma.achievement.findMany({
            where: { userId: session.user.id },
            orderBy: { occurredAt: "desc" },
            include: {
                content: true, // Include resume bullets, LinkedIn, Twitter
            },
        });

        // ============================================================
        // STEP 3: Build Markdown Document
        // ============================================================

        // Header
        let markdown = `# My Open Source Achievements\n\n`;
        markdown += `Generated by Blazzic on ${new Date().toLocaleDateString("en-US", {
            month: "long",
            day: "numeric",
            year: "numeric",
        })}\n\n`;
        markdown += `---\n\n`;

        // ============================================================
        // STEP 4: Add Summary Stats Section
        // TODO: Calculate totals for impressive overview
        // ============================================================
        const totalScore = achievements.reduce((sum: number, a: any) => sum + a.score, 0);
        markdown += `## Summary\n\n`;
        markdown += `- **Total Achievements:** ${achievements.length}\n`;
        markdown += `- **Impact Score:** ${totalScore}\n`;
        markdown += `- **PRs Merged:** ${achievements.filter((a: any) => a.type === "pr_merged").length}\n\n`;
        markdown += `---\n\n`;

        // ============================================================
        // STEP 5: Add Achievements Section
        // TODO: List each achievement with details
        // ============================================================
        markdown += `## Achievements\n\n`;

        for (const achievement of achievements) {
            // Achievement title
            markdown += `### ${achievement.title}\n\n`;
            
            // Repository link
            markdown += `**Repository:** [${achievement.repoOwner}/${achievement.repoName}](${achievement.repoUrl})\n\n`;
            
            // Metadata
            markdown += `**Type:** ${achievement.type.replace("_", " ")}\n\n`;
            markdown += `**Score:** ${achievement.score}\n\n`;
            markdown += `**Date:** ${new Date(achievement.occurredAt).toLocaleDateString()}\n\n`;

            // Description
            if (achievement.description) {
                markdown += `**Description:** ${achievement.description}\n\n`;
            }

            // ============================================================
            // STEP 6: Add Generated Content for Each Achievement
            // TODO: Include resume bullet, LinkedIn, Twitter if exists
            // ============================================================
            
            // Resume bullet (blockquote style)
            const resumeContent = achievement.content.find(
                (c: any) => c.format === "resume_bullet"
            );
            if (resumeContent) {
                markdown += `**Resume Bullet:**\n\n`;
                markdown += `> ${resumeContent.content}\n\n`;
            }

            // LinkedIn post (code block)
            const linkedinContent = achievement.content.find(
                (c: any) => c.format === "linkedin_post"
            );
            if (linkedinContent) {
                markdown += `**LinkedIn Post:**\n\n`;
                markdown += `\`\`\`\n${linkedinContent.content}\n\`\`\`\n\n`;
            }

            // Twitter thread (code block)
            const twitterContent = achievement.content.find(
                (c: any) => c.format === "twitter_thread"
            );
            if (twitterContent) {
                markdown += `**Twitter Thread:**\n\n`;
                markdown += `\`\`\`\n${twitterContent.content}\n\`\`\`\n\n`;
            }

            // Separator between achievements
            markdown += `---\n\n`;
        }

        // ============================================================
        // STEP 7: Return as Downloadable File
        // TODO: Set headers for file download with timestamp
        // ============================================================
        return new NextResponse(markdown, {
            headers: {
                "Content-Type": "text/markdown",
                "Content-Disposition": `attachment; filename="Blazzic-achievements-${new Date()
                    .toISOString()
                    .split("T")[0]}.md"`,
            },
        });
    } catch (error) {
        console.error("Export error:", error);
        return NextResponse.json(
            { error: "Failed to export achievements" },
            { status: 500 }
        );
    }
}